### PR TITLE
Update to 2013-08-13 API

### PR DESCRIPTION
**Pull request by irwinb**
Contains breaking changes because of changes to the Customer and Card models.  Changes to the Plan/Token models are non-breaking.

### CODE REVIEW

**Comment by elithrar** [comment]
This likely happened after @irwinb's PR, but Charges, Customers and Invoices accept additional `metadata` with the object: https://stripe.com/docs/api#metadata 

The current PR only adds support to this for `Customers`.

(read: I'm more than happy to submit a PR that leverages Irwin's, but it'd be nice to see his PR merged into master first. Or at least a `2013-08-13` API branch to maintain backwards compatibility.

**Comment by bradrydzewski** [comment]
sorry for the hold up, code has been merged. Thanks for bringing the library and unit tests up to date!

**Comment by irwinb** [comment]
@elithrar, waiting for your PR :)

**Comment by elithrar** [comment]
@irwinb Roger that! I've just updated my fork against master and I should have some time to work on it/test it this week.

**Pull request merged**
